export const courseData = [
    {
        name: "History of Architecture 1",
        description: "Presentation of knowledge state of the most important directions and trends in architectutre, urban planning and arts from Antiquity to the Romanesque Architecture.",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/1/History%20of%20Architecture%201-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Fundamentals of Architectural Design with Elements of Ergonomics 1",
        description: "architectural design for the implementation of simple tasks, in particular: simple facilities taking into account the basic needs of users, single- and multi-family housing, service facilities in residential complexes, public utility facilities in an open landscape or in an urban environment",
        ECTS: 2,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/1/Fundamentals%20of%20Architectural%20Design%20with%20Elements%20of%20Ergonomics%201-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Drawing, painting, sculpture 1",
        description: "Developing the skills to use light in creating moods with the use of drawing means.",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/1/Drawing,%20Painting,%20Sculpture%201-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "History of Architecture 2",
        description: "Explains the continuity of European architectural tradition in the plane of evolution of the needs, technique and beauty in the period from Gothic to the Renaissance. Defines relations between the technical capabilities and the level of satisfaction of material and spiritual needs.",
        ECTS: 2,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/2/History%20of%20Architecture%202-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Fundamentals of Architectural Design with Elements of Ergonomics 2",
        description: " familiarization with changes in architecture resulting from the development of culture and societies (transition from an industrial society to an information society) that took place in the 20th century and are still ongoing today",
        ECTS: 2,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/2/Fundamentals%20of%20Architectural%20Design%20with%20Elements%20of%20Ergonomics%202-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Civil Engineering 1",
        description: "Learning about the components of buildings, the functioning of the building structure as a whole; getting acquainted with loads occurring in the building, load differentiation depending on purpose of the object.",
        ECTS: 2,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/2/Civil%20Engineering%201-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Fundamentals of Urban Design Project",
        description: "Learning about urban composition and get to know the basic problems of urban planning. Practice of shaping the form of urban spaces, independent creation and presentation of solutions for complexes of interrelated interiors",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/3/Fundamentals%20of%20Urban%20Design%20(project)-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Civil Engineering 2",
        description: "Provide knowledge about the conditions and possibilities of using particular building finishes. Presentation and demonstration of the advantages of designing in the 'building module'; presentation of types of types of woodwork",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/3/Civil%20Engineering%202-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Foundations of urban design",
        description: "Practice feeling and drawing an urban interior, to realize the influence of the changes introduced in the space on its reception. Learn about urban composition and get to know the basic problems of urban planning.",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/3/Architectural%20Design%20of%20Residential%20Buildings%201-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Architectural Design of Service Facilities",
        description: "Learning the methodology when developing architectural concepts with a low degree of complexity, including service facilities",
        ECTS: 3,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Architektura%20_%20Architecture/stacjonarne/studia%20pierwszego%20stopnia/4/Architectural%20Design%20of%20Service%20Facilieies_1%20(project)-ang.pdf",
        faculties: "Architecture",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Mathematics",
        description: "The aim of subject is introduction to complex numbers and their some practical applications. Differential and integral calculus of one variable are presented together with their applications in mathematics and chemistry.",
        ECTS: 5,
        semester: "winter",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/1/Matematyka-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Physics",
        description: "Advanced knowledge within classical mechanics, thermodynamics, gravity and electrical interactions with special emphasis on their applications in studied subject. Basic knowledge about constructing, principles of working and lifetime of modern engineering systems.",
        ECTS: 5,
        semester: "winter",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/1/Fizyka-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Engineering graphics",
        description: "Providing students with basic knowledge of the principles and rules of technical drawing and descriptive geometry, to the extent specified by the program content appropriate to the field of study. Developing student's reading skills and independent drawing designs of machine parts used in the chemical and related industries.",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/1/Grafika%20in%C5%BCynierska-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Organic chemistry",
        description: " Provide students with basic knowledge of organic chemistry, to the extent specified by the content of the curriculum of the chemical and process engineering field of study.",
        ECTS: 5,
        semester: "winter",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/3/Chemia%20organiczna-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Process thermodynamics",
        description: "Mastering knowledge of the thermodynamic foundations of chemical and process engineering operations and processes: balancing principles and thermodynamics in closed and open systems in stationary and non-stationary conditions, in reversible and irreversible proccesses.",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/3/Termodynamika%20procesowa-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Physical chemistry",
        description: "To familiarise students with basic problems in physical chemistry and electrochemistry at the academic level in the field of: chemical kinetics, simple and complex reactions, homo - and heterogeneous catalysis and electrolysis, type of half-cells and type of cells. ",
        ECTS: 5,
        semester: "summer",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/4/Chemia%20fizyczna-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Organic technology",
        description: "Obtaining knowledge of organic chemical technology.",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/6/Technologia%20organiczna-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Fundamentals of electrochemical technology",
        description: "The aim of the course is to familiarize students with an overview of technical electrochemistry methods and develop skills for their practical application.",
        ECTS: 5,
        semester: "summer",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/5/Podstawy%20technologii%20elektrochemicznej-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Engineering graphics",
        description: "Practical knowledge of computer aided design. In addition, the student acquires the ability to perform drawings using basic functions in the AutoCad program. AutoCad 2D course , basic level.",
        ECTS: 2,
        semester: "summer",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/2/przedmioty%20obieralne/Grafika%20in%C5%BCynierska%20(AutoCad%20podstawowy)-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Management and Marketing",
        description: "To familiarize students with the basic achievements in the field of management and marketing theory.To acquaint students with the specifics of management and promoting enterprises in a market economy.",
        ECTS: 3,
        semester: "summer",
        ECTScard: "https://put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20chemiczna%20i%20procesowa/stacjonarne/studia%20pierwszego%20stopnia/2/przedmioty%20obieralne/Przedmiot%20humanistyczny%20obieralny%20II%20(Zarz%C4%85dzanie%20i%20marketing)-ang.pdf",
        faculties: "Chemical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Structural Fire Engineering",
        description: "The course objective is to deliver the knowledge of material and structural behaviour in fire and modelling of recognized in fire physical processes taking into account reciprocal dependences between them.",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Advanced Construction Materials",
        description: "Functions of building materials. Basic parameters and criteria for selecting building materials. New trends in cement and concrete technology. Self-compacting and photocatalytic concretes. HSC, UHSC and fibro concrete. Transparent and glass concrete. ",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Engineering Surveying",
        description: "Legal basis for geodetic and cartographic materials, information databases and measurement activities applicable in the investment process. Theoretical basis and the latest technical solutions in the field of measurements and the development of observational data. The course of implementation measurements: network, staking out methods and as-built inventory of completed buildings and technical infrastructure.",
        ECTS: 2,
        semester: "winter",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Numerical Analysis",
        description: "Presentation of the basics of experimental research aimed at determining the mechanical properties of building materials (steel, other metals, concrete, glass and others) in a complex state of stress, a wide range of deformation rates and temperatures, Presentation of the measures of deformation, deformation velocity and stress used in nonlinear constitutive relationships used for modeling building materials.",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Structural Dynamics",
        description: "Equations of motion of structures treated as discrete systems. Equations of motion written in terms of state variables. Models of chosen types of structures. Damping models. Free vibration analysis, dynamic characteristics of structures with and without damping.",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Computational Mechanics",
        description: "Mathematical modelling in Civil Engineering. Fundamentals of continuum mechanics for Civil Engineering. Introduction to advanced Finite Element Method (FEM) with applications in Civil Engineering. Modelling of building constructions as three-dimensional bodies (constructions of an arbitrary shape) and as two-dimensional bodies (walls, retaining walls, dams). Modelling of plate structures.",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Advanced Concrete Structures I",
        description: "Analysis of reinforced concrete structures according to Eurocode 2. Types of silos and tanks. Loads acting on silos and tanks and their calculation in combination. Differential equilibrium equations of shells. Surface structures as spherical and conical shells.",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Elasticity and Plasticity",
        description: "Elements of tensor calculus. Stress tensor. Analysis of stress state, principal stresses and directions. Equilibrium equations and boundary conditions. Description of movement, Lagrange and Euler coordinates. Analysis of strain state. Strain tensor and its interpretation. Geometrical equations. Constitutive relations, generalized Hooke's law. Principal strains and directions. Lame and Michell's-Beltrami's equations. Energy principles.",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Metal Structures 1",
        description: "Methods for constructing and dimensioning frame systems (static diagrams, loads, dimensioning of eccentrically compressed columns and frame transoms, connection details). Principles of construction and dimensioning of concentrations in hall buildings.",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Design of Structures",
        description: "Duties and requirements for civil engineers. The main principles and provisions of building law regarding design. Performing static calculations of construction elements (climatic and service loads). Rules for dimensioning structures made of wooden, steel and concrete elements according to European standards (ULS and SLS).",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://erasmus-fte.put.poznan.pl/in_en/courses/_civil-engineering-ce/",
        faculties: "Civil Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Technolgies of Software Development",
        description: "Course objective 1. Provide students knowledge regarding .NET Framework and corresponding technologies, creating websites using Ruby on Rails framework, scripting, dynamic, functional, distributed, cloud programming.2. Develop students' skills in solving problems related to creating application using different technologies 3. Present students a set of development technologies for modeling data layer, designing interface layer, defining communication layer between several applications 4. Develop students' teamwork skills in the context of developing software systems 5. Develop students' skills to learn new technologies",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2021_2022/Informatyka/stacjonarne/studia%20drugiego%20stopnia/Software%20Engineering%20(In%C5%BCynieria%20oprogramowania)/1/Technologies%20of%20Software%20Development-ang.pdf",
        faculties: "Computing and Telecommunications",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Software Design and Modeling",
        description: "Course objective The objective for this course is to give the students knowledge on object-oriented software modeling and design, based on re-using commonly accepted best practices and design patterns elaborated and published in literature. Additionally, the course is expected to develop skills in evaluating the quality of software design and source code, and the use of selected mechanisms available in object-oriented programming languages.",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2021_2022/Informatyka/stacjonarne/studia%20drugiego%20stopnia/Software%20Engineering%20(In%C5%BCynieria%20oprogramowania)/1/Software%20Design%20and%20Modeling-ang.pdf",
        faculties: "Computing and Telecommunications",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Polish",
        description: "The aim of the course is to learn the basics of communication in Polish while studying in Poland. The emphasis is on practical knowledge of the language and communication as well as learning about Polish culture.",
        ECTS: 2,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2021_2022/Informatyka/stacjonarne/studia%20drugiego%20stopnia/Software%20Engineering%20(In%C5%BCynieria%20oprogramowania)/1/Polish-ang.pdf",
        faculties: "Computing and Telecommunications",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "New trends in multimedia technologies",
        description: "1. Providing students with basic knowledge of multimedia technologies and the social consequences of their use 2. Developing students' skills in acquiring knowledge about new trends in multimedia technologies and popularizing knowledge in this field 3. Shaping students' communication skills using multimedia tools",
        ECTS: 3,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2021_2022/Informatyka/stacjonarne/studia%20drugiego%20stopnia/Software%20Engineering%20(In%C5%BCynieria%20oprogramowania)/1/New%20Trends%20in%20Multimedia%20Technologies-ang.pdf",
        faculties: "Computing and Telecommunications",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Database Performance",
        description: "1. Provide students with knowledge regarding database server performance evaluation and management techniques. 2. Develop students’ skills in solving problems related to performance issues in database applications.",
        ECTS: 5,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2021_2022/Informatyka/stacjonarne/studia%20drugiego%20stopnia/Software%20Engineering%20(In%C5%BCynieria%20oprogramowania)/1/Database%20Performance-ang.pdf",
        faculties: "Computing and Telecommunications",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Mathematics",
        description: "The acquisition and consolidation of examples of basic mathematical concepts and acquire the ability to use the mathematical apparatus",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20zarz%C4%85dzania/stacjonarne/studia%20pierwszego%20stopnia/1/Matematyka-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Computer-aided Engineering Drawing",
        description: "",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20zarz%C4%85dzania/stacjonarne/studia%20pierwszego%20stopnia/1/Komputerowa%20grafika%20in%C5%BCynierska-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Managerial Accounting",
        description: "The objective of the course is to acquire knowledge, skills and competences in the field of concepts, issues, regularities and methods of solving problems in the field of managerial accounting.",
        ECTS: 3,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20zarz%C4%85dzania%20_%20Engineering%20Management/stacjonarne/studia%20drugiego%20stopnia/Managing%20Enterprise%20of%20the%20Future%20(Zarz%C4%85dzanie%20przedsi%C4%99biorstwem%20przysz%C5%82o%C5%9Bci)/1/Managerial%20Accounting-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Production Management",
        description: "The essence of production management. Classification of processes in an enterprise, an organized process. Parameters and norms of production management, space modeling the manufacturing process, control planes.",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20zarz%C4%85dzania/stacjonarne/studia%20pierwszego%20stopnia/6/Zarz%C4%85dzanie%20produkcj%C4%85-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Finances",
        description: "Understanding the basic mechanisms of the functioning of the financial system in the national economy and its impact on financial decisions taken by individual business entities. Developing students' skills in solving problems arising in the selection of the source of financing.",
        ECTS: 5,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20zarz%C4%85dzania/stacjonarne/studia%20pierwszego%20stopnia/2/Finanse-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Microeconomis",
        description: "To familiarize students with the basic concepts of the theory of microeconomics. Transfer of knowledge about the principles of market operation.",
        ECTS: 5,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Inżynieria%20zarządzania%20_%20Engineering%20Management/stacjonarne/studia%20pierwszego%20stopnia/4/Human%20Resources%20Management-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Basics of management",
        description: "Teaching a system of basic concepts used to describe the management process and models, methods and principles explaining basic aspects of the management phenomenon.",
        ECTS: 5,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Inżynieria%20zarządzania%20_%20Engineering%20Management/stacjonarne/studia%20pierwszego%20stopnia/1/Basics%20of%20Management-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Advanced Functions of MS Office",
        description: "Students should acquire proficiency in using a spreadsheet in the field of engineering calculations, including selected optimization issues. They should also acquire the ability to freely and efficiently use a text editor to edit documents.",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Inżynieria%20zarządzania%20_%20Engineering%20Management/stacjonarne/studia%20pierwszego%20stopnia/1/Advanced%20functions%20of%20MS%20Office-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Organizational Behavior",
        description: "Understand main functions of ogranized team work systems, methods of analyzing and assessing their functioning",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Inżynieria%20zarządzania%20_%20Engineering%20Management/stacjonarne/studia%20pierwszego%20stopnia/1/Organizational%20behavior-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Computer-aided Engineering Drawing",
        description: "Familiarization with electrical, architectural and construction drawings and machine construction based on the information from the machine drawing. The ability to read technical drawing.",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Inżynieria%20zarządzania%20_%20Engineering%20Management/stacjonarne/studia%20pierwszego%20stopnia/1/Computer-aided%20Engineering%20Drawing-ang.pdf",
        faculties: "Engineering Management",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Gas engines",
        description: "Students should have basic information about: thermodynamic, mechanics, fluid mechanics, strength of materials",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Renewable Energy Sources",
        description: "To familiarize students with the basic issues in the field of renewable energy, including renewable energy sources (sun, wind, tides, geothermal energy, water), restrictions and dependencies between sources. ",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Heat and Power Technology",
        description: "Basic knowledge in the field of mechanics, thermodynamics and fluid mechanics and knowledge about construction of energetic machines. Student should also have skills required to solve engineering problems with scientifically valid methodologies. ",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Applied thermodynamics",
        description: "The knowledge of the thermodynamics (the basic engineering course), fluid mechanics, heat exchange, physics, mathematics.",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Generation of electric energy",
        description: "Student has a basic knowledge of the basics of energy conversion and energy machine and equipment. He knows the basics of electrical engineering and power engineering. Understand the basic principles of operation of the machines and know the basic construction of conventional energy equipment.",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Gas turbines",
        description: "Basic knowledge from thermodynamics, fluid mechanics, mechanics, and construction of energetic engines. Can use the scientific method for problem solving, experimenting, and making conclusions.",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Energy management",
        description: "Basic knowledge of thermodynamics (energy, exergy and substantial balances) as well as of elementary economics (costs, profits, economy efficiency measures).",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Programming in data analysis",
        description: "Basic knowledge of the basics of computer science, data analysis and Python environment",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Environmental engineering",
        description: "Solving engineering problems with the use of scientific methods and find relevant information in literature, on the Internet, in data bases, and in other sources .",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Energy Efficient Buildings",
        description: "Basics of architectural design, basics of building physics and general construction. Skills in the ability to assess phenomena in the field of heat transfer in buildings and operating computer programs including Excel, Word, SketchUp.",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://isie.put.poznan.pl/en/node/3599",
        faculties: "Environmental Engineering and Energy",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Engineering drawing",
        description: "Mastership of basic principles of image construction of spatial objects on the plane. Training of spatial imagination.",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/1/Grafika%20in%C5%BCynierska-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Informatics",
        description: "Understanding theoretical and practical problems associated with the design and application engineering databases in the enterprise.",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/1/Informatyka-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Ceramics and glass",
        description: ".Development students' knowledge related to relationships between technologic processes, technologic conditions, structures, properties and applications of ceramic and glassy materials.",
        ECTS: 3,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/1/Podstawy%20nauki%20o%20materia%C5%82ach-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Electrotechnics",
        description: "Acquiring knowledge about the principle of operation of electrical machines and devices, ability to analyze and solve equations describing simple electrical systems.",
        ECTS: 2,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/3/Elektrotechnika-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Materials welding technologies",
        description: "Knowledge of technologies and methods of welding materials.",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/5/Technologia%20%C5%82%C4%85czenia%20materia%C5%82%C3%B3w-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Mechanics",
        description: "Cognizing and understanding the main concepts and laws of mechanics. Developing the skills of modeling mechanical systems and solving problems related to the movement and the equilibrium of mechanical systems. ",
        ECTS: 5,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/2/Mechanika-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Metallurgy and foundry",
        description: "Understanding the basic phenomena and processes related to obtaining metal materials and shaping products (castings) from them",
        ECTS: 3,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/2/Metalurgia%20i%20odlewnictwo-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Corrosion and protection against corrosion",
        description: "Providing to students information about corrosion phenomena and damages, and methods of corrosion protection.",
        ECTS: 2,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/4/Korozja%20i%20ochrona%20przed%20korozj%C4%85-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Crystallography",
        description: "e basic knowledge of crystalline structures of materials. The basic knowledge of crystallography.",
        ECTS: 3,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/4/Krystalografia-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Composites",
        description: "Getting the knowledge of the types, structure, production methods, application and operating conditions of composite materials.",
        ECTS: 3,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/In%C5%BCynieria%20materia%C5%82owa/stacjonarne/studia%20pierwszego%20stopnia/4/Kompozyty-ang.pdf",
        faculties: "Materials Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Analytical Mechanics",
        description: "This course aims to provide a comprehensive understanding of the fundamental concepts of force, energy, and momentum, and their applications in engineering.",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Computational Systems and Tool in Engineering",
        description: "This course exposes students to a variety of engineering software and programming languages, enabling them to model, analyze, and solve complex engineering systems and scenarios.",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Systems Engineering",
        description: "This course introduces students to the principles and methodologies of designing, managing, and optimizing complex engineering systems. It bridges the gap between traditional mechanical engineering disciplines and a holistic approach to engineering design.",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Production Management",
        description: "This course offers students an understanding of the principles of efficient planning, scheduling, and control of production activities to ensure smooth operations and maximum efficiency.",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Machine vision in manufacturing technology",
        description: "The course covers the fundamentals of image processing, analysis, and computer vision algorithms, as well as the integration of these systems into a manufacturing environment for quality control, automation, and process optimization.",
        ECTS: 6,
        semester: "winter",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Elements of Optronics",
        description: "",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Noise Control in Industry",
        description: "Noise Control in Industry is a specialized course that emphasizes the importance of managing and controlling industrial noise for the safety and comfort of workers and the surrounding environment. This course combines principles of acoustics, materials science, and engineering design to provide practical strategies for noise reduction in various industrial settings.",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "FEM Acoustical Modeling in COMSOL Multiphysics",
        description: "FEM Acoustical Modeling in COMSOL Multiphysics is an advanced course that combines principles of acoustics with the application of Finite Element Method (FEM) for modeling and solving acoustic problems. The course leverages the COMSOL Multiphysics software, a powerful tool for simulating physical phenomena, to model acoustical scenarios and analyze their results.",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Hydraulics and Pneumatics",
        description: "Students learn about the design, analysis, and control of systems and components related to fluid power, focusing on both hydraulic (liquid-based) and pneumatic (gas-based) systems.",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Processing of polymeric materials",
        description: " The course aims to provide students with a comprehensive understanding of the manufacturing techniques and principles behind converting raw polymeric materials into finished products.",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://wim.put.poznan.pl/artykul/erasmus-incomming-subjects",
        faculties: "Mechanical Engineering",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Mathematics I ",
        description: "The aim is to acquaint with methods and applications of differential and integral calculus of single and double variable functions",
        ECTS: 8,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/1/Mathematics%20I-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Micro and small enterprise management",
        description: "The course introduces students to the basic concepts of management in which they live and provides them with an understanding of how economics and enterprenuership relate to the other aspects of their everyday life. ",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/1/przedmioty%20obieralne/Elective%20humanistic1%20%20Micro%20and%20small%20enterprise%20management-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Project management",
        description: "The graduate has basic knowledge of management (including quality management) and running a business. The graduate knows and understands the basic economic conditions of different types of activities related to the given qualification. ",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/1/przedmioty%20obieralne/Elective%20humanistic1%20%20Project%20management-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Control basics",
        description: "The aim of the course is to teach students to analyze control systems and present basic knowledge concerning continuous-time systems.",
        ECTS: 4,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/3/Control%20basics%20in3sem-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Signals and Dynamic Systems",
        description: "Teaching students methods of generating and analyzing basic deterministic and stochastic signals in the time and frequency domain using applications in the Matlab programming language. Acquiring and consolidating the skills of spectral analysis of signals using a discrete Fourier transform - DFT or FFT and interpretation of results depending on the sampling frequency of analog signals",
        ECTS: 5,
        semester: "winter",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/3/Signals%20and%20dynamic%20systems-Lab-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Information engineering",
        description: "Learning object-oriented programming, familiarization with basic libraries and tools supporting PC programming.",
        ECTS: 4,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/2/Information%20engineering-Lab-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Circuit theory",
        description: "Getting to know the theoretical and practical problems of electrical engineering. Acquiring the ability to analyze selected electrical circuits of direct and alternating current.",
        ECTS: 7,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/2/Electrical%20engineering%20-%20Circuit%20theory-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Theoretical mechanics and mechanics of materials",
        description: "The aim is to make students familiar with the theoretical fundamentals of general mechanics and mechanics of materials",
        ECTS: 5,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/2/Theoretical%20mechanics%20and%20mechanics%20of%20materials-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Robotics",
        description: "Acquaintance of knowledge about robot kinematics: Direct and Inverse kinemtics for positions and velocities of robot manipulators",
        ECTS: 2,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl/cards/2022_2023/Automatyka%20i%20robotyka%20_%20Automatic%20Control%20and%20Robotics/stacjonarne/studia%20pierwszego%20stopnia/4/Robotics%20in4sem-ang.pdf",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    },
    {
        name: "Term Design",
        description: "Development of skills of practical use of acquired knowledge. Further development of skills of analysing and solving problems by themself. Forming skills of team work to solve research problem.",
        ECTS: 6,
        semester: "summer",
        ECTScard: "https://www.put.poznan.pl",
        faculties: "Automatic Control and Robotics",
        ratings: [],
        ratedBy: [],
    }
]