version: "3.8"

services:
  reverse-proxy:
    build: 
      context: ./reverse-proxy
    container_name: reverse-proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - front
      - back

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    container_name: sds-front-prod
    restart: always
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    container_name: sds-back-prod
    restart: always
    depends_on: 
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sdsDB
