name: ci

on:
  push:
    branches: [ main, feature/ci ]
  pull_request:
    branches: [ main, feature ]

jobs:
  build-test-front:
    name: Build and test front
    defaults:
      run:
        working-directory: ./front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setupe Node 18.12.1
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1

      - name: Install dependencies
        run: npm install
          
      - name: Build
        run: npm run build:ci
          
      - name: Test   
        run: npm run test:ci
        
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: ./dist
          
      - name: Archive code coverage results
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy_coverage_results
          path: ./coverage
  
  build-test-back:
    steps:
      name: buid and test back
      defaults:
        run:
          working-directory: ./back
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: setup node 18.12.1
          uses: actions/setup-node@v2
          with:
            node-version: 18.12.1

        - name: install dependencies
          run: npm install

        - name: build
          run: npm run build

        - name: test
          run: npm run test:cov

        - name: Archive build
          if: success()
          uses: actions/upload-artifact@v2
          with:
            name: deploy_dist
          path: ./dist

        - name: Archive code coverage results
          if: success()
          uses: actions/upload-artifact@v2
          with:
            name: deploy_coverage_results
            path: ./coverage